# documentation label
documentation:
  - ./README.md
  - src/config/swagger.json

# adds the test label
test:
  - src/**/*.test.ts

enhancement:
  - src/**/*

database:
  - '**.ddl'
  - '**.sql'

endpoints:
  - src/services/**

middleware:
  - src/middleware/**
