# documentation label
documentation:
  - ./README.md
  - swagger.json

# adds the test label
test:
  - src/**/*.test.ts

enhancement:
  - src/**/*

database:
  - '**.ddl'
  - '**.sql'

endpoints:
  - services/**

middleware:
  - middleware/**
