/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-09-22 22:59:48 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/dash -t session -t users -s public
 *
 */


export namespace sessionFields {
    export type sid = string;
    export type sess = Object;
    export type expire = Date;

}

export namespace usersFields {
    export type username = string;
    export type password = string;
}

export interface users {
    uname: usersFields.username;
    password: usersFields.password;

}

export namespace invoiceFields {
    export type invoiceId = number;
    export type nextInId = number;
    export type deliveryDate = Date;
}

export interface invoices {
    InId: invoiceFields.invoiceId;
    nextInId: invoiceFields.nextInId;
    DeliveryDate: invoiceFields.deliveryDate;
}
