/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2019-11-12 19:09:27 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:5432/requesttopay -t invoiceitems -t items -t invoice -t entity -t warehousecontents -t orders -s requesttopay
 *
 */

export namespace invoiceitemsFields {
    export type inid = number;
    export type iid = number;
    export type price = number;
    export type quantity = number;

}

export interface invoiceitems {
    inid: invoiceitemsFields.inid;
    iid: invoiceitemsFields.iid;
    price: invoiceitemsFields.price;
    quantity: invoiceitemsFields.quantity;

}

export namespace itemsFields {
    export type iid = number;
    export type name = string;
    export type sid = number;
    export type price = number;

}

export interface items {
    iid: itemsFields.iid;
    name: itemsFields.name;
    sid: itemsFields.sid;
    price: itemsFields.price;

}

export namespace invoiceFields {
    export type inid = number;
    export type nextinid = number | null;
    export type deliverydate = Date;

}

export interface invoice {
    inid: invoiceFields.inid;
    nextinid: invoiceFields.nextinid;
    deliverydate: invoiceFields.deliverydate;

}

export namespace entityFields {
    export type eid = number;
    export type name = string;
    export type billingaddress = string;
    export type password = string;

}

export interface entity {
    eid: entityFields.eid;
    name: entityFields.name;
    billingaddress: entityFields.billingaddress;
    password: entityFields.password;

}

export namespace warehousecontentsFields {
    export type sid = number;
    export type iid = number;
    export type location = string;
    export type quantity = number | null;

}

export interface warehousecontents {
    sid: warehousecontentsFields.sid;
    iid: warehousecontentsFields.iid;
    location: warehousecontentsFields.location;
    quantity: warehousecontentsFields.quantity;

}

export namespace ordersFields {
    export type oid = number;
    export type inid = number;
    export type did = number;
    export type sid = number;
    export type cid = number;
    export type orderdate = Date;

}

export interface orders {
    oid: ordersFields.oid;
    inid: ordersFields.inid;
    did: ordersFields.did;
    sid: ordersFields.sid;
    cid: ordersFields.cid;
    orderdate: ordersFields.orderdate;

}
