/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2019-11-12 19:09:27 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:5432/requesttopay -t invoiceitems -t items -t invoice -t entity -t warehousecontents -t orders -s requesttopay
 *
 */

export namespace invoiceitemsFields {
    export type inid = number;
    export type iid = number;
    export type price = number;
    export type quantity = number;

}

export interface invoiceitems {
    InID: invoiceitemsFields.inid;
    IID: invoiceitemsFields.iid;
    Price: invoiceitemsFields.price;
    Quantity: invoiceitemsFields.quantity;

}

export namespace itemsFields {
    export type iid = number;
    export type name = string;
    export type sid = number;
    export type price = number;

}

export interface items {
    IID: itemsFields.iid;
    Name: itemsFields.name;
    SID: itemsFields.sid;
    Price: itemsFields.price;

}

export namespace invoiceFields {
    export type inid = number;
    export type nextinid = number | null;
    export type deliverydate = Date;

}

export interface invoice {
    InID: invoiceFields.inid;
    NextInID: invoiceFields.nextinid;
    DeliveryDate: invoiceFields.deliverydate;

}

export namespace entityFields {
    export type eid = number;
    export type name = string;
    export type billingaddress = string;
    export type password = string;

}

export interface entity {
    EID: entityFields.eid;
    Name: entityFields.name;
    BillingAddress: entityFields.billingaddress;
    Password: entityFields.password;

}

export namespace warehousecontentsFields {
    export type sid = number;
    export type iid = number;
    export type location = string;
    export type quantity = number | null;

}

export interface warehousecontents {
    SID: warehousecontentsFields.sid;
    IID: warehousecontentsFields.iid;
    Location: warehousecontentsFields.location;
    Quantity: warehousecontentsFields.quantity;

}

export namespace orderFields {
    export type oid = number;
    export type inid = number;
    export type did = number;
    export type sid = number;
    export type cid = number;
    export type orderdate = Date;

}

export interface order {
    OID: orderFields.oid;
    InID: orderFields.inid;
    DID: orderFields.did;
    SID: orderFields.sid;
    CID: orderFields.cid;
    OrderDate: orderFields.orderdate;

}
